### ISSUE TITLE
Simulation fails if alert counters are not reported

### ISSUE THREAD

**Issue by maleiter** [HDLUtils/hdlregression#11]
When using HDLRegression without UVVM, I can't call report_alert_counters(FINAL);
But if I do not call report_alert_counters(FINAL) at the end of the testbench, all tests fail. 
Is this intended?
Is it possible to use HDLRegression without UVVM?

**Comment by HDLUtils** [comment]
Hi,
Yes, you can use any verification framework you want.
By default, HDLRegression will run as used by a UVVM testbench, but you can change this behaviour as descried in section 4.3.13 - set_default_check_string().


Br.

**Comment by maleiter** [comment]
Thanks, so according to the documentation (Note in section 4.3.15, revision 0.41.0), "SUCCESS" is used as the default keyword. If I simply `report "SUCCESS";` at the end of the testbench instead of `report_alert_counters();` the tests still fail.
After calling `hr.set_result_check_string("SUCCESS")` in the Python script, the tests pass. 

Is there any other information parsed from the report_alert_counters() output except the SUCCESS Keyword?

**Comment by HDLUtils** [comment]
Currently, there are only UVVM testbenches that are analyzed in more detail. A UVVM testbench can have three outcomes: FAIL, PASS, and PASS with minor alerts. These outcomes are determined based on the UVVM alert summary. Other testbenches and frameworks must provide a distinct indication for a successful test, something that would not be found in the log otherwise.

Br
